services:
  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin123
      - INFLUXDB_ORG=my-org
      - INFLUXDB_BUCKET=my-bucket
      - INFLUXDB_TOKEN=my-token

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: timescaledb
    environment:
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
    ports:
      - "5436:5432"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb

